# as per http://badsyntax.co/post/travis-ci-and-bower
language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g browserify
  - npm install -g testling
  - npm install -g mocha
  - npm install -g bower
  - npm isntall -g gulp
  - bower install
  - gulp
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start